---
- name: debug shell
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/common.yaml

  roles:
    - role: kubectl
      vars:
        kubectl_setup: yes
        kubectl_configure: yes

  tasks:
    - name: 💾 Write out kubeconfig + AWS creds for interactive debugging
      copy:
        dest: /opt/k8s/debug_env.sh
        mode: "0755"
        content: |
          #!/usr/bin/env bash
          export AWS_ACCESS_KEY_ID={{ kubectl_aws_access_key_id }}
          export AWS_SECRET_ACCESS_KEY={{ kubectl_aws_secret_access_key }}
          export AWS_SESSION_TOKEN={{ kubectl_aws_session_token }}
          export KUBECONFIG={{ kubectl_config_path }}

    - name: ⏸️ Hold this pod open for interactive debugging
      pause:
        seconds: 86400
        prompt: "Debug shell ready – CTRL+C to exit"
