---
- name: Provision the fabric-ca servers
  gather_facts: true
  hosts: tag_Component_bastion
  become: no
  become_user: root
  vars_files:
    - vars/common.yaml
    - vars/fabric_network_vars.yaml
  roles:
    - role: k8s_fabric_ca
      k8s_fabric_ca_org: org1
      k8s_fabric_ca_keyfile: priv_sk
      k8s_fabric_ca_separate_pvc: true
      k8s_fabric_ca_az: "{{k8s_fabric_network_azs[0]}}"
      k8s_fabric_ca_crypto_config: "{{k8s_fabric_crypto_config}}"
      k8s_fabric_ca_crypto_config_secret_name: fabric-crypto-config
